name: "Post-Integration: Regression Test"

on:
  workflow_call:
    inputs:
      key:
        required: true
        type: string
        description: 'The JIRA Issue Key.'
      repository:
        required: true
        type: string
        description: 'Repository of regression test in format <organization>/<repository>.'
      ref:
        required: false
        type: string
        default: master
        description: 'The branch, tag or SHA to checkout.'
      base-url:
        required: true
        type: string
      project:
        required: true
        type: string
        description: 'Maven project under monorepo of regression test.'
      report-portal-endpoint:
        required: true
        type: string
      upload-artifact:
        required: false
        type: boolean
        description: |
          Optional. It will take some artifact storage quota.
          Disable if not needed.
        default: true
    secrets:
      token:
        required: true
        description: 'Personal access token (PAT) used to fetch the repository.'
      report-portal-api-key:
        required: true

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.token }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '${{ inputs.project }}/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Regression
        run: |
          NOW=$(date +%d%m%Y)
          mvn -pl ${{ inputs.project }} verify -q \
              -Dwebdriver.base.url=${{ inputs.base-url }} \
              -Drp.endpoint=${{ inputs.report-portal-endpoint }} \
              -Drp.api.key=${{ secrets.report-portal-api-key }} \
              -Drp.description="Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}" \
              -Drp.attributes=release:${NOW}

      - name: Uploading Result Data
        if: ${{ inputs.upload-artifact && (success() || failure()) }}
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: ${{ inputs.project }}/target/site
          retention-days: 3
