name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  prerelease: # make sure the action works on a clean machine without building
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch:
          - feature/jira-123-branch
          - feature/jira-123
          - jira-123-branch
          - jira-123
    steps:
      - uses: actions/checkout@v2
      - id: prerelease
        uses: ./prerelease
        with:
          branch: ${{ matrix.branch }}
          push: false
      - run: if [[ "$KEY" == "JIRA-123" ]]; then exit 0; else exit 1; fi
        env:
          KEY: ${{ steps.prerelease.outputs.key }}
      - run: if [[ "$TAG" == "1.1.0-rc.0" ]]; then exit 0; else exit 1; fi
        env:
          TAG: ${{ steps.prerelease.outputs.tag }}

  release:
    runs-on: ubuntu-20.04
    environment: staging:JIRA-123
    steps:
      - uses: actions/checkout@v2
      - run: |
          git tag JIRA-123
          git tag 1.1.0-rc.0
      - id: release
        uses: ./release
        with:
          key: JIRA-123
          token: ${{ secrets.RELEASE_TOKEN }}
          push: false
      - run: if [[ "$TAG" == "1.1.0" ]]; then exit 0; else exit 1; fi
        env:
          TAG: ${{ steps.release.outputs.tag }}
